name: "Update Algolia Search Index"

on: 
  push:
    branches:
      - main

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - run: bundle exec jekyll algolia
      env:
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
        